name: OpenWrt-CI-x86_64 IPK

on:
  workflow_dispatch:
  
jobs:
  build_openwrt:
    name: Build OpenWrt ipk
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Get tags
        run : |
          git fetch --tags https://github.com/openwrt/openwrt.git
          git push --tags
          echo "tag=$(git tag | sort | tail -1)" >> $GITHUB_ENV

      - name: Checkout to tag
        uses: actions/checkout@v4
        with:
          ref: ${{ env.tag }}

      - name: Git Clone
        run : |
          git clone https://github.com/MIAOBUSI/luci-app-adguardhome package/luci/luci-app-adguardhome
          # git clone https://github.com/khrozelfist/3proxy-openwrt package/net/3proxy
          # git clone https://github.com/v2rayA/v2raya-openwrt package/net/v2raya

      - name: Update feeds
        run : |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Generate configuration file
        run : |
          ver=$(echo ${{ env.tag }} | cut -c 2-)
          rm -f ./.config*
          wget -O .config https://downloads.openwrt.org/releases/$ver/targets/x86/64/config.buildinfo

          sed -i '/CONFIG_KERNEL_BUILD_DOMAIN/d' ./.config
          sed -i '/CONFIG_KERNEL_BUILD_USER/d' ./.config

          make defconfig

      - name: Make download
        run : |
          make download -j8 || make download -j1 V=s
          rm -rf $(find ./dl/ -size -1024c)
          df -h

      - name: Compile toolchain
        run : |
          make -j$(nproc) tools/install
          make -j$(nproc) toolchain/install

      - name: Compile IPK
        run : |
          make -j$(nproc) package/luci/luci-app-adguardhome/compile

      - name: Prepare IPK
        run : |
          mkdir -p ./artifact/package
          cp -rf $(find ./bin/packages/ -type f -name "*.ipk") ./artifact/package/

      - name: Deliver IPK
        uses: actions/upload-artifact@v4
        with:
          name: IPK
          path: ./bin/packages/
